entitlements/strictly-audited/admin.txt:
  sha256sum: 6bae3e6f508bf60d77afcb76c401557fd7a0d82a374fba3a29439d85c39bb45c
  format:
    - txt
  reviews:
    enabled: true
    labels:
      - Periodic Audit
    days: 182
    strategy: manager
    title: Admin access
