---
danhoerst:
  status:
    - employee
  title: GitHub
  manager: hubot # for example purposes, we report to a bot
grantbirki:
  status:
    - employee
  title: GitHub
  manager: hubot # for example purposes, we report to a bot
