name: manager

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  manager:
    name: manager
    runs-on: ubuntu-latest

    steps:
      - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # pin@v1.172.0
        with:
          bundler-cache: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install yq
        run: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

      - name: manager review
        run: echo "managers=$(examples/manager_review)" >> $GITHUB_ENV

      - uses: delivery-much/actions-assigner@ef457092b82f63fe69b1b36279a4d9a3946859c5 # pin@v1
        if: "${{ env.managers != '' }}"
        with:
          reviewers: "${{ env.managers }}"
