name: manager

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  manager:
    name: manager
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # pin@v1.172.0
        with:
          bundler-cache: true

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@d3f05c95a4dcb7025d07972df3cfcf9c1c53c00d # pin@v2.4.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          file_output_only: "true"

      - name: manager review
        id: manager_review
        run: |
          bundle exec ruby examples/manager_review.rb
          echo "managers=$(cat managers.txt)" >> $GITHUB_OUTPUT
          rm managers.txt

      - uses: delivery-much/actions-assigner@ef457092b82f63fe69b1b36279a4d9a3946859c5 # pin@v1
        if: steps.manager_review.outputs.managers != '$NO_MANAGERS_FOUND$'
        with:
          reviewers: ${{ steps.manager_review.outputs.managers }}
