name: manager

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  manager:
    name: manager
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@28c4deda893d5a96a6b2d958c5b47fc18d65c9d3 # pin@v1.213.0
        with:
          bundler-cache: true

      # - name: manager review
      #   id: manager_review
      #   run: echo "managers=$(examples/manager_review)" >> $GITHUB_OUTPUT

      #   # this step is likely broken and needs a dedicated GitHub PAT
      # - uses: delivery-much/actions-assigner@ef457092b82f63fe69b1b36279a4d9a3946859c5 # pin@v1
      #   if: steps.manager_review.outputs.managers != ''
      #   continue-on-error: true
      #   with:
      #     reviewers: ${{ steps.manager_review.outputs.managers }}
